name: CI: build Android debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages + accept licenses
        run: |
          COMPILE_SDK=$(grep -Rho "compileSdk\s*[0-9]\+" app/build.gradle* | sed 's/[^0-9]//g' | tail -1 || true)
          [ -z "$COMPILE_SDK" ] && COMPILE_SDK=34
          echo "Using compileSdk=$COMPILE_SDK"
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-$COMPILE_SDK"
          yes | sdkmanager --licenses

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Assemble Debug
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: traccar-client-debug
          path: app/build/outputs/apk/debug/*.apk
